tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "git"
brew "node"
brew "pnpm"
brew "postgresql", restart_service: true
cask "dbeaver-community"
cask "discord"
cask "docker"
cask "google-chrome"
cask "insomnia"
cask "spotify"
cask "syncalicious"
cask "visual-studio-code"
cask "whatsapp"
